language: python

python:
  - "2.7"

env:
  global:
    secure: GStdSQ10ql5pKTEH0HGpZsZjlQnX2CgRAccZ0Pr4aTk7KbaCpZyAJQXdBTSaM1qzZo5QFn5tmIwBXljI4nncdwhAMM5NIKSTZwY+wmpCrLvRI0WrJarfGuK8lwV4NrPWkfCd8qfKx/6MERgrCvCUviXLFZf3YamB5o8icuur7jo=

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
  - conda install --yes -n condaenv pip
  - source activate condaenv
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose pytest flake8 colorama flask sphinx basemap lxml sqlalchemy==0.9.9 mock mpi4py
  - pip install suds-jurko
  - pip install geographiclib
  - pip install progressbar
  - pip install flask-cache
  - pip install geojson
  - pip install future
  - pip install "joblib>=0.8.0a3"
  - pip install --no-deps pyqtgraph
  # The theme from the repository it also more up to date.
  - pip install https://github.com/snide/sphinx_rtd_theme/archive/master.zip
  - pip install --no-deps https://github.com/obspy/obspy/archive/master.zip
  - pip install --no-deps https://github.com/krischer/wfs_input_generator/archive/master.zip

install:
  - pip install --no-deps .

script:
  - cd $TRAVIS_BUILD_DIR; py.test
  - cd $TRAVIS_BUILD_DIR/doc; make html

# Upload any potentially produced diffs and produced images to imgur after a test failure.
after_failure:
  - wget "http://imgur.com/tools/imgurbash.sh"
  - "find /tmp/pytest-* -name \"*.png\" | xargs -I % bash imgurbash.sh %"
after_success:
  - bash $TRAVIS_BUILD_DIR/.travis-update-gh-pages.sh
