language: python

python:
- '3.6'

env:
  global:
    secure: k4sk3/LUdr/Ck//eCrGI5hEK1O4YWNww8F+KvUZhs+WgUlJYeLfbT8V4Zx5BDSkXa1CA5HeWJrQExwz5T+FFAhc8AqyQ8ujyENgNKY8N+8J93VYY/64fl+XJmZL0tukNw0bZMAIlbQHxWWafk5FHrJZbPwUrjH/SdJzonSgDNMWDw9skJ8Ti8p8dK8UVkPL5yQObU/8JPQcUCqxm+VVp38QS60AVGYQ7Uv93EbS9Y1aGknj2s1/CRrFHQJQZRXf7hCF4ZGnwbF74lTx40ERzYCOxlTDckGONmG3jGaiKk5bCIL9Np5OQc3IsDMz8qp5Seu7jYw9tj0QG8WWMxJsG1uBtegNuIhDj8d1rwdwzQVM5ztx1nBKL+P+yS5xsfkz1FaRCHbfUo6re7moJYqMTSID0/ghkcj9L43yjMvw84dKkjq1r2GHhrJZoWV6vSpHUgVNARYEQFZDZnn0sQXMTLOYvOlILmPCnuTosvqgZ70A1YOJjcV3nYIePZMOkZnMkTNr/PbIgBb9+JHGa27oOBVBejG61XV2czC0VtQjqY+by4PUAcaiHEHLRxBaNl4RdCbAo14hFtM+uLIIscUuUBoaTQqow7rcs62GjOFRMbdJSOBa1mBtagP4ygTdXaMeS28Siya5MEBMGfl1rFWPhMH1cMOmgcyDhu1ZBJM/Tk2g=

before_install:
- wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b -p $HOME/miniconda
- export PATH=$HOME/miniconda/bin:$PATH
- conda config --add channels conda-forge
- conda update --yes conda
- conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
- conda install --yes -n condaenv
- source activate condaenv
- conda install --yes -c conda-forge numpy==1.13.1 obspy nomkl basemap progressbar2 colorama joblib pytest nose mock pyqt
- conda install --yes -c conda-forge pyqtgraph pip sphinx sphinx_rtd_theme numexpr ipython dill prov seaborn
- pip install geographiclib flask-cache geojson flake8 toml==0.9.2
- cd ..
- git clone https://github.com/SalvusHub/pyexodus.git
- cd pyexodus
- pip install .
- cd ..
- conda install --yes -c spectraldns h5py-parallel
- git clone https://github.com/SeismicData/pyasdf.git
- cd pyasdf
- pip install .
- cd ..
- git clone https://gitlab.com/Salvus/salvus_seismo
- cd salvus_seismo/py
- pip install .


install:
- cd $TRAVIS_BUILD_DIR; pip install .

script:
- cd $TRAVIS_BUILD_DIR/lasif/whl; pip install salvus_wave-0.0.0-cp36-cp36m-linux_x86_64.whl
- cd $TRAVIS_BUILD_DIR; py.test
- cd $TRAVIS_BUILD_DIR/doc; make html
after_failure:

- wget "https://raw.githubusercontent.com/tremby/imgur.sh/master/imgur.sh"
- find /tmp/pytest-* -name "*.png" | xargs -I % bash imgur.sh %
after_success:

- bash $TRAVIS_BUILD_DIR/.travis-update-gh-pages.sh
