language: python

python:
  - "2.7"

env:
  global:
    secure: GStdSQ10ql5pKTEH0HGpZsZjlQnX2CgRAccZ0Pr4aTk7KbaCpZyAJQXdBTSaM1qzZo5QFn5tmIwBXljI4nncdwhAMM5NIKSTZwY+wmpCrLvRI0WrJarfGuK8lwV4NrPWkfCd8qfKx/6MERgrCvCUviXLFZf3YamB5o8icuur7jo=

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
  - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
  - conda install --yes -n condaenv pip
  - source activate condaenv
  - conda install --yes -c obspy obspy nomkl basemap progressbar colorama joblib pytest nose mock pip python=$TRAVIS_PYTHON_VERSION mpi4py
  - conda uninstall --yes pyflakes flake8 pep8
  - pip install geographiclib flask-cache geojson flake8
  - pip install https://github.com/krischer/wfs_input_generator/archive/master.zip

install:
  - pip install --no-deps .

script:
  - cd $TRAVIS_BUILD_DIR; py.test
  - cd $TRAVIS_BUILD_DIR/doc; make html

# Upload any potentially produced diffs and produced images to imgur after a test failure.
after_failure:
  - wget "http://imgur.com/tools/imgurbash.sh"
  - "find /tmp/pytest-* -name \"*.png\" | xargs -I % bash imgurbash.sh %"
after_success:
  - bash $TRAVIS_BUILD_DIR/.travis-update-gh-pages.sh
