language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
env: MATPLOTLIBRC=$HOME
before_install:
  - sudo apt-get install -qq gfortran python-dev python-numpy python-scipy python-suds python-lxml python-sqlalchemy
  # Install matplotlib with pip to get a recent version.
  - pip install --use-mirrors matplotlib
  - wget http://sourceforge.net/projects/matplotlib/files/matplotlib-toolkits/basemap-1.0.7/basemap-1.0.7.tar.gz/download -O basemap-1.0.7.tar.gz
  - tar -xzf basemap-1.0.7.tar.gz
  - cd basemap-1.0.7/geos-3.3.3
  - export GEOS_DIR=$HOME/geos
  - ./configure --prefix=$GEOS_DIR
  - make install
  - cd ..
  - python setup.py install
  - pip install https://github.com/yarikoptic/coveralls-python/archive/master.zip
  - pip install --use-mirrors geographiclib
  - pip install --use-mirrors requests
  - pip install --use-mirrors progressbar
  - pip install --use-mirrors flake8
  - pip install --use-mirrors colorama
  - pip install --no-deps https://github.com/obspy/obspy/archive/master.zip
  - pip install --no-deps https://github.com/krischer/wfs_input_generator/archive/master.zip
  # The MATPLOTLIBRC environment variable is set to $HOME
  - "echo \"backend:AGG\" > $HOME/matplotlibrc"
  - python -c "import matplotlib; print matplotlib.matplotlib_fname()"
script:
  - cd lasif; py.test
install:
  # Python's multiprocessing shared memory requires /dev/shm with r/w access.
  # The VM's in travis do not offer this.
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
  - pip install  --no-deps .
