language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install -qq gfortran python-dev python-numpy python-scipy python-matplotlib python-suds python-lxml python-sqlalchemy python-m2crypto python-mpltoolkits.basemap
  - pip install https://github.com/yarikoptic/coveralls-python/archive/master.zip
  - pip install --use-mirrors geographiclib
  - pip install --use-mirrors requests
  - pip install --use-mirrors progressbar
  - pip install --use-mirrors flake8
  - pip install --use-mirrors colorama
  - pip install --no-deps https://github.com/obspy/obspy/archive/master.zip
  - pip install --no-deps https://github.com/krischer/wfs_input_generator/archive/master.zip
script:
  - cd lasif; py.test
install:
  # Python's multiprocessing shared memory requires /dev/shm with r/w access.
  # The VM's in travis do not offer this.
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
  - pip install  --no-deps .
